export const LangStrings = {
  en: {
    banner: {
      slogan: 'Our passion is Concrete',
      text: 'We operate as a dynamically developing company in the construction market. As a structural builder, we have become a key player in many investments across the country over the years.',
    },
    header: {
      h0: 'Home',
      h1: 'About Us',
      h2: 'Projects',
      h3: 'Career',
      h4: 'Contact',
    },
    about: {
      subTitle: 'about us',
      title: 'Committed to High Quality Service',
      f_0_title: 'Foundation',
      f_0_text: 'DAKI-ÉP Kft. was founded in 2018, our main activity is the construction of residential and non-residential buildings.',
      f_1_title: 'Always dedicated',
      f_1_text: 'It is important for us to be reliable partners in structural construction for our customers. We guarantee outstanding performance, accurate and professional work.',
    },
    numbers: {
      slogan: "Our Services",
      title: "Our everyday lives in numbers",
      n_0_title: 'people is employed per year',
      n_1_title: 'of concrete are processed per year',
      n_2_title: 'of rebar are installed per year',
      n_3_title: 'of shutter are installed per year',
    },
    featured: {
      title: "In our work we have pride, quality is what we provide",
      description1: "Our staff are well-trained, helpful, purposeful professionals with good problem-solving skills. They have a high load capacity and several years of professional experience.",
      description2: "The technical management is performed by our civil engineers and foremen with many years of domestic and international professional experience.",
    },
    clients: {
      slogan: "Meet Our Clients",
      title: "Our reputation is as solid as concrete",
    },
    gallery: {
      slogan: 'Our Projects',
      title: 'Successful projects we are proud of',
      button: 'Explore More',
    },
    career: {
      slogan: "Join Us",
      title: "Meet our currently open positions",
      button: "Apply",

      n_1_title: 'Design Quality & performance',
      n_1_description: 'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
      n_2_title: 'Design Quality & performance',
      n_2_description: 'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
      n_3_title: 'Layout and organized layers',
      n_3_description: 'Get working experience to work with this amazing team & in future want to work together for bright future projects and also make deposit to freelancer.',
    },
    contact: {
      title: "Contact Us to get the best offers",
      description: "In urgent cases, feel free to contact us via the e-mail address below",
      button1: "Business",
      button2: "Career",
      button3: "Contact Us",
      button4: "Join Us",
      paceholder: "Enter your e-mail...",
    },
    project: {
      pr_0_slogan: 'Helping you and your house become better acquainted',
      pr_0_project_type: 'Contruction',
      pr_0_header: 'Creating a sustainable future through building preservation, green architecture and smart design',
      pr_0_p1: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
      pr_0_p2: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
    
      pr_1_slogan: 'Helping you and your house become better acquainted',
      pr_1_project_type: 'Contruction',
      pr_1_header: 'Creating a sustainable future through building preservation, green architecture and smart design',
      pr_1_p1: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
      pr_1_p2: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
    
      pr_2_slogan: 'Helping you and your house become better acquainted',
      pr_2_project_type: 'Contruction',
      pr_2_header: 'Creating a sustainable future through building preservation, green architecture and smart design',
      pr_2_p1: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
      pr_2_p2: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
    
      pr_3_slogan: 'Helping you and your house become better acquainted',
      pr_3_project_type: 'Contruction',
      pr_3_header: 'Creating a sustainable future through building preservation, green architecture and smart design',
      pr_3_p1: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
      pr_3_p2: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
    
      pr_4_slogan: 'Helping you and your house become better acquainted',
      pr_4_project_type: 'Contruction',
      pr_4_header: 'Creating a sustainable future through building preservation, green architecture and smart design',
      pr_4_p1: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
      pr_4_p2: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
    
      pr_5_slogan: 'Helping you and your house become better acquainted',
      pr_5_project_type: 'Contruction',
      pr_5_header: 'Creating a sustainable future through building preservation, green architecture and smart design',
      pr_5_p1: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
      pr_5_p2: 'Designers think everything done by someone else is awful, and that they could do it better themselves, which explains why I designed my own living room carpet, I suppose. the architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression.',
    },
  },
  hu: {
    banner: {
      slogan: 'A mi szenvedélyünk beton',
      text: 'Dinamikusan fejlődő vállalatként működünk az építőipari piacon. Szerkezetépítőként számos beruházás meghatározó szereplőjévé váltunk az évek során az ország egész területén.',
    },
    header: {
      h0: 'Kezdőlap',
      h1: 'Rólunk',
      h2: 'Projektjeink',
      h3: 'Karrier',
      h4: 'Kapcsolat',
    },
    about: {
      subTitle: 'rólunk',
      title: 'Magas minőségű munka iránti elkötelezettség',
      f_0_title: 'Alapítás',
      f_0_text: 'A DAKI-ÉP Kft. 2018-ban alakult, fő tevékenységünk Lakó és nem lakóépületek építése.',
      f_1_title: 'Elkötelezettség',
      f_1_text: 'Számunkra fontos, hogy a szerkezetépítésben megbízható partnerei legyünk a megrendelőink számára. Kiemelkedő teljesítményű, pontos és szakszerű munkavégzést garantálunk. ',
    },
    numbers: {
      slogan: "Szolgáltatásaink",
      title: "Mindennapjaink számokban",
      n_0_title: 'embert foglalkoztatunk évente',
      n_1_title: 'betont dolgozunk be évente',
      n_2_title: 'betonacélt építünk be évente',
      n_3_title: 'zsalut építünk be évente',
    },
    clients: {
      slogan: "Partnereink",
      title: "Hírnevünk szilárd, mint a beton",
    },
    featured: {
      title: "A tökéletesség nem a mennyiségben van, hanem a minőségben",
      description1: "Munkatársaink jól képzett, segítőkész, céltudatos szakemberek, jó problémamegoldó képességgel. Nagy teherbírással és több éves szakmai tapasztalattal rendelkeznek.",
      description2: "A műszaki irányítást több éves hazai illetve nemzetközi szakmai tapasztalattal rendelkező építőmérnökeink és művezetőink végzik.",
    },
    gallery: {
      slogan: 'Projektjeink',
      title: 'Sikeres projektek amikre büszkék vagyunk',
      button: 'Többi megtekintése',
    },
    career: {
      slogan: "Csatlakozz hozzánk",
      title: "Ismerje meg a jelenleg nyitott pozícióinkat",
      button: "Jelentkezés",

      n_1_title: 'ÉPÍTÉSVEZETŐ',
      n_1_section1: 'Feladatok, amelyek Rád várnak: ',
      n_1_job_1: 'Építési munkák műszaki, szakmai irányítása',
      n_1_job_2: 'Ütemterv, pénzügyi ütemezések készítése és ezek betartatása',
      n_1_job_3: 'Kapcsolattartás alvállalkozókkal, megrendelővel, szakági tervezőkkel, műszaki ellenőrrel, beszállítókkal',
      n_1_job_4: 'Anyagrendelések, eszközök, emberi erőforrások koordinálása',
      n_1_job_5: 'Építési megbeszéléseken való aktív részvétel és közreműködés',
      n_1_job_6: 'Alvállalkozók helyszíni közvetlen irányítása, ellenőrzése',
      n_1_section2: 'A munkakör betöltéséhez elengedhetetlen: ',
      n_1_needs_1: 'Minimum 1-3 év építésvezetői szakmai tapasztalat',
      n_1_needs_2: 'Közvetlen, nyitott, kommunikatív személyiség',
      n_1_needs_3: '„B” kategóriás jogosítvány',

      n_2_title: 'MŰSZAKI ELŐKÉSZÍTŐ',
      n_2_section1: 'Feladatok, amelyek Rád várnak: ',
      n_2_job_1: 'Építési munkák műszaki, szakmai irányítása',
      n_2_job_2: 'Ütemterv, pénzügyi ütemezések készítése és ezek betartatása',
      n_2_job_3: 'Kapcsolattartás alvállalkozókkal, megrendelővel, szakági tervezőkkel, műszaki ellenőrrel, beszállítókkal',
      n_2_job_4: 'Anyagrendelések, eszközök, emberi erőforrások koordinálása',
      n_2_job_5: 'Építési megbeszéléseken való aktív részvétel és közreműködés',
      n_2_job_6: 'Alvállalkozók helyszíni közvetlen irányítása, ellenőrzése',
      n_2_section2: 'Te vagy az ideális jelölt, amennyiben: ',
      n_2_needs_1: 'Megbízhatóan, nagyfokú önállósággal és felelősségteljesen dolgozol',
      n_2_needs_2: 'Kiváló a szervező- és a problémamegoldó képességed',
      n_2_needs_3: 'Magabiztos MS Office gyakorlattal rendelkezel',

      n_3_title: 'MŰVEZETŐ',
      n_3_section1: 'Feladatok, amelyek Rád várnak: ',
      n_3_job_1: 'Építési munkák műszaki, szakmai irányítása',
      n_3_job_2: 'Ütemterv, pénzügyi ütemezések készítése és ezek betartatása',
      n_3_job_3: 'Kapcsolattartás alvállalkozókkal, megrendelővel, szakági tervezőkkel, műszaki ellenőrrel, beszállítókkal',
      n_3_job_4: 'Anyagrendelések, eszközök, emberi erőforrások koordinálása',
      n_3_job_5: 'Építési megbeszéléseken való aktív részvétel és közreműködés',
      n_3_job_6: 'Alvállalkozók helyszíni közvetlen irányítása, ellenőrzése',
      n_3_section2: 'A munkakör betöltéséhez elengedhetetlen:: ',
      n_3_needs_1: 'Minimum 1 év szakmai tapasztalat',
      n_3_needs_2: 'Közvetlen, nyitott, kommunikatív személyiség',
      n_3_needs_3: '„B” kategóriás jogosítvány',
    },
    contact: {
      title: "Vedd fel velünk a kapcsolatot a legjobb ajánlatokért",
      description: "Sürgős esetekben keress fel minket bátran a lenti e-mail címen keresztül",
      button1: "Üzlet",
      button2: "Karrier",
      button3: "Érdeklődnék",
      button4: "Csatlakoznék",
      paceholder: "Írd be az e-mail címed...",
    },
    project: {
      pr_0_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_0_project_type: 'Építkezés',
      pr_0_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_0_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_0_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      
      pr_0_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_0_project_type: 'Építkezés',
      pr_0_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_0_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_0_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
    
      pr_1_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_1_project_type: 'Építkezés',
      pr_1_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_1_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_1_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
    
      pr_2_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_2_project_type: 'Építkezés',
      pr_2_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_2_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_2_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
    
      pr_3_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_3_project_type: 'Építkezés',
      pr_3_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_3_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_3_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
    
      pr_4_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_4_project_type: 'Építkezés',
      pr_4_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_4_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_4_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
    
      pr_5_slogan: 'Segítséget nyujt a házának a jobb megismerésében',
      pr_5_project_type: 'Építkezés',
      pr_5_header: 'Fenntartható jövő megteremtése az épületek megőrzése, a zöld építészet és az intelligens tervezés révén',
      pr_5_p1: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
      pr_5_p2: 'A tervezők szörnyűnek tartanak mindent, amit valaki más tett, és hogy ők maguk is jobban meg tudnák csinálni, ami megmagyarázza, miért terveztem saját nappali szőnyeget. az építész sem dionüszoszi, sem apollinai állapotot nem képvisel: itt az akarat hatalmas cselekedete, az akarat mozgatja a hegyeket, az erős akarat mámorosa, amely művészi kifejezést követel.',
    },
  },
};
