export const LangStrings = {
  en: {
    banner: {
      slogan: 'Our passion is Concrete',
      text: 'We operate as a dynamically developing company in the construction market. As a structural builder, we have become a key player in many investments across the country over the years.',
    },
    header: {
      h0: 'Home',
      h1: 'About Us',
      h2: 'Projects',
      h3: 'Career',
      h4: 'Contact',
    },
    about: {
      subTitle: 'about us',
      title: 'Committed to High Quality Service',
      f_0_title: 'Foundation',
      f_0_text: 'DAKI-ÉP Kft. was founded in 2018, our main activity is the construction of residential and non-residential buildings.',
      f_1_title: 'Always dedicated',
      f_1_text: 'It is important for us to be reliable partners in structural construction for our customers. We guarantee outstanding performance, accurate and professional work.',
    },
    numbers: {
      slogan: "Our Services",
      title: "Our everyday lives in numbers",
      tons: " tons",
      n_0_title: 'people is employed per year',
      n_1_title: 'of concrete are processed per year',
      n_2_title: 'of rebar are installed per year',
      n_3_title: 'of shutter are installed per year',
    },
    featured: {
      title: "In our work we have pride, quality is what we provide",
      description1: "Our staff are well-trained, helpful, purposeful professionals with good problem-solving skills. They have a high load capacity and several years of professional experience.",
      description2: "The technical management is performed by our civil engineers and foremen with many years of domestic and international professional experience.",
    },
    clients: {
      slogan: "Meet Our Clients",
      title: "Our reputation is as solid as concrete",
    },
    gallery: {
      slogan: 'Our Projects',
      title: 'Successful projects we are proud of',
      button: 'Explore More',
    },
    career: {
      slogan: "Join Us",
      title: "Meet our currently open positions",
      button: "Apply",

      n_1_title: 'CONSTRUCTION MANAGER',
      n_1_section1: 'Tasks waiting for you:',
      n_1_job_1: 'Technical and professional management of construction works',
      n_1_job_2: 'Schedule, prepare financial schedules and adhere to them',
      n_1_job_3: 'Keeping in touch with subcontractors, customer, industry designers, technical inspector, suppliers',
      n_1_job_4: 'Coordination of material orders, tools, human resources',
      n_1_job_5: 'Active participation in construction discussions',
      n_1_job_6: 'On-site direct management and control of subcontractors',
      n_1_section2: 'Essential conditions to fill the job: ',
      n_1_needs_1: 'Minimum 1-3 years of professional experience as a construction manager',
      n_1_needs_2: 'Direct, open, communicative personality',
      n_1_needs_3: 'Category "B" license',

      n_2_title: 'QUANTITY SURVEYOR',
      n_2_section1: 'Tasks waiting for you: ',
      n_2_job_1: 'Calculation of quantities and ratios based on construction plans',
      n_2_job_2: 'Creating tenders',
      n_2_job_3: 'Participation in project documentation',
      n_2_job_4: 'Keeping in touch with project manager, subcontractors, suppliers ',
      n_2_job_5: 'Coordination of materials, tools, human resources ',
      n_2_section2: 'You are the ideal candidate if: ',
      n_2_needs_1: 'You work reliably, with a high degree of independence and responsibly',
      n_2_needs_2: 'You have excellent organizing and problem solving skills',
      n_2_needs_3: 'You have confident MS Office experiences',

      n_3_title: 'FOREMAN',
      n_3_section1: 'Tasks waiting for you:',
      n_3_job_1: 'Technical and professional management of construction works',
      n_3_job_2: 'Keeping in touch with subcontractors, customer, industry designers, technical inspector, suppliers',
      n_3_job_3: 'Coordination of material orders, tools, human resources',
      n_3_job_4: 'Active participation in construction discussions',
      n_3_job_5: 'On-site direct management and control of subcontractors',
      n_3_section2: 'Essential conditions to fill the job: ',
      n_3_needs_1: 'Minimum 1-3 years of professional experience as a construction manager',
      n_3_needs_2: 'Direct, open, communicative personality',
      n_3_needs_3: 'Category "B" license',
    },
    contact: {
      title: "Contact Us to get the best offers",
      description: "In urgent cases, feel free to contact us via the e-mail address below",
      button1: "Business",
      button2: "Career",
      button3: "Contact Us",
      button4: "Join Us",
      paceholder: "Enter your e-mail...",
      toast: "We will contact you soon!",
      toast_error: "The e-mail address is not valid!",
    },
    project: {
      date: 'DATE',
      client: 'CLIENT',
      type: 'PROJECT TYPE',
      location: 'LOCATION',
      pr_1_slogan: 'Your project is our business',
      pr_1_name: 'BÜK Nestlé Hungaria Kft - Boilerhouse substructures',
      pr_1_project_type: 'Hall Contruction',
      pr_1_header: 'Boiler house foundation and ascending structure construction works have been carried out by our company within this project.',
      pr_1_p1: '',
      pr_1_p2: '',
    
      pr_2_slogan: 'The road to the future…is under construction',
      pr_2_name: 'Zalaegerszeg - Bridge Contruction',
      pr_2_project_type: 'Bridge Contruction',
      pr_2_header: 'Our company carried out the construction of many works of art. From the pile clamping beam to the entire bridge head structure.',
      pr_2_p1: '',
      pr_2_p2: '',
    
      pr_3_slogan: 'Concrete results',
      pr_3_name: 'BÜK Nestlé Hungaria Kft - Construction of test buildings',
      pr_3_project_type: 'Structural Contruction',
      pr_3_header: 'Test Construction work for foundation and ascending structures of buildings and service buildings has been carried out by our company within this project.',
      pr_3_p1: '',
      pr_3_p2: '',

      blog_slogan: 'SIMILAR PROJECTS',
      blog_title: 'Explore our projects for your business solution',
    },
  },
  hu: {
    banner: {
      slogan: 'Szenvedélyünk a beton',
      text: 'Dinamikusan fejlődő vállalatként működünk az építőipari piacon. Szerkezetépítőként számos beruházás meghatározó szereplőjévé váltunk az évek során az ország egész területén.',
    },
    header: {
      h0: 'Kezdőlap',
      h1: 'Rólunk',
      h2: 'Projektjeink',
      h3: 'Karrier',
      h4: 'Kapcsolat',
    },
    about: {
      subTitle: 'rólunk',
      title: 'Magas minőségű munka iránti elkötelezettség',
      f_0_title: 'Alapítás',
      f_0_text: 'A DAKI-ÉP Kft. 2018-ban alakult, fő tevékenységünk Lakó és nem lakóépületek építése.',
      f_1_title: 'Elkötelezettség',
      f_1_text: 'Számunkra fontos, hogy a szerkezetépítésben megbízható partnerei legyünk a megrendelőink számára. Kiemelkedő teljesítményű, pontos és szakszerű munkavégzést garantálunk. ',
    },
    numbers: {
      slogan: "Szolgáltatásaink",
      title: "Mindennapjaink számokban",
      tons: " tonna",
      n_0_title: 'embert foglalkoztatunk évente',
      n_1_title: 'betont dolgozunk be évente',
      n_2_title: 'betonacélt építünk be évente',
      n_3_title: 'zsalut építünk be évente',
    },
    clients: {
      slogan: "Partnereink",
      title: "Hírnevünk szilárd, mint a beton",
    },
    featured: {
      title: "A tökéletesség nem a mennyiségben van, hanem a minőségben",
      description1: "Munkatársaink jól képzett, segítőkész, céltudatos szakemberek, jó problémamegoldó képességgel. Nagy teherbírással és több éves szakmai tapasztalattal rendelkeznek.",
      description2: "A műszaki irányítást több éves hazai illetve nemzetközi szakmai tapasztalattal rendelkező építőmérnökeink és művezetőink végzik.",
    },
    gallery: {
      slogan: 'Projektjeink',
      title: 'Sikeres projektek amikre büszkék vagyunk',
      button: 'Többi megtekintése',
    },
    career: {
      slogan: "Csatlakozz hozzánk",
      title: "Ismerje meg a jelenleg nyitott pozícióinkat",
      button: "Jelentkezés",

      n_1_title: 'ÉPÍTÉSVEZETŐ',
      n_1_section1: 'Feladatok, amelyek Rád várnak: ',
      n_1_job_1: 'Építési munkák műszaki, szakmai irányítása',
      n_1_job_2: 'Ütemterv, pénzügyi ütemezések készítése és ezek betartatása',
      n_1_job_3: 'Kapcsolattartás alvállalkozókkal, megrendelővel, szakági tervezőkkel, műszaki ellenőrrel, beszállítókkal',
      n_1_job_4: 'Anyagrendelések, eszközök, emberi erőforrások koordinálása',
      n_1_job_5: 'Építési megbeszéléseken való aktív részvétel és közreműködés',
      n_1_job_6: 'Alvállalkozók helyszíni közvetlen irányítása, ellenőrzése',
      n_1_section2: 'A munkakör betöltéséhez elengedhetetlen: ',
      n_1_needs_1: 'Minimum 1-3 év építésvezetői szakmai tapasztalat',
      n_1_needs_2: 'Közvetlen, nyitott, kommunikatív személyiség',
      n_1_needs_3: '„B” kategóriás jogosítvány',

      n_2_title: 'MŰSZAKI ELŐKÉSZÍTŐ',
      n_2_section1: 'Feladatok, amelyek Rád várnak: ',
      n_2_job_1: 'Mennyiségek és arányok számítása kiviteli tervek alapján',
      n_2_job_2: 'Árajánlatok készítése',
      n_2_job_3: 'Projekt-dokumentálásban való részvétel ',
      n_2_job_4: 'Kapcsolattartás projektvezetővel, alvállalkozókkal, beszállítókkal ',
      n_2_job_5: 'Anyagok, eszközök, emberi erőforrás koordinálása ',
      n_2_section2: 'Te vagy az ideális jelölt, amennyiben: ',
      n_2_needs_1: 'Megbízhatóan, nagyfokú önállósággal és felelősségteljesen dolgozol',
      n_2_needs_2: 'Kiváló a szervező- és a problémamegoldó képességed',
      n_2_needs_3: 'Magabiztos MS Office gyakorlattal rendelkezel',

      n_3_title: 'MŰVEZETŐ',
      n_3_section1: 'Feladatok, amelyek Rád várnak: ',
      n_3_job_1: 'Építési munkák műszaki, szakmai irányítása',
      n_3_job_2: 'Kapcsolattartás alvállalkozókkal, megrendelővel',
      n_3_job_3: 'Anyagrendelések, eszközök, emberi erőforrások koordinálása',
      n_3_job_4: 'Építési megbeszéléseken való aktív részvétel és közreműködés',
      n_3_job_5: 'Alvállalkozók helyszíni közvetlen irányítása, ellenőrzése',
      n_3_section2: 'A munkakör betöltéséhez elengedhetetlen: ',
      n_3_needs_1: 'Minimum 1 év szakmai tapasztalat',
      n_3_needs_2: 'Közvetlen, nyitott, kommunikatív személyiség',
      n_3_needs_3: '„B” kategóriás jogosítvány',
    },
    contact: {
      title: "Vedd fel velünk a kapcsolatot a legjobb ajánlatokért",
      description: "Sürgős esetekben keress fel minket bátran a lenti e-mail címen keresztül",
      button1: "Üzlet",
      button2: "Karrier",
      button3: "Érdeklődnék",
      button4: "Csatlakoznék",
      paceholder: "Írd be az e-mail címed...",
      toast: "Hamarosan felvesszük Önnel a kapcsolatot!",
      toast_error: "Az e-mail cím nem megfelelő!",
    },
    project: {
      date: 'DÁTUM',
      client: 'KLIENS',
      type: 'PROJECT TÍPUS',
      location: 'HELYSZÍN',
   
      pr_1_slogan: 'Ön megálmodja, mi megvalósítjuk',
      pr_1_name: 'BÜK Nestlé Hungaria Kft - Kazánház alépítmények',
      pr_1_project_type: 'Csarnoképítés',
      pr_1_header: 'Kazánház alapozási és felmenőszerkezetek építési munkáit végezte társaságunk a projekt keretein belül. ',
      pr_1_p1: '',
      pr_1_p2: '',
    
      pr_2_slogan: 'A jövőbe vezető út… építés alatt áll',
      pr_2_name: 'Zalaegerszeg - Hídépítés',
      pr_2_project_type: 'Hídépítés ',
      pr_2_header: 'Társaságunk végezte számos műtárgy építését. A cölöpösszefogó gerendától a hídfőn át a pályalemezek kivitelezési munkálatáig. ',
      pr_2_p1: '',
      pr_2_p2: '',
    
      pr_3_slogan: 'Szakértelem és minőség',
      pr_3_name: 'GÖD Samsung SDI Magyarország Zrt. - Tesztépületek kivitelezése',
      pr_3_project_type: 'Szerkezetépítés',
      pr_3_header: 'Tesztépületek és kiszolgáló épületek alapozási és felmenő szerkezeteinek kivitelezési munkáit végezte társaságunk a projekt során. ',
      pr_3_p1: '',
      pr_3_p2: '',
    
      blog_slogan: 'HASONLÓ MUNKÁINK',
      blog_title: 'Fedezze fel további projektjeinket is',
    },
  },
};
