export default [
  {
    id: '0',
    name: 'Creative Market',
    slogan: 'Helping you and your house become better acquinted',
    date: 'April 10, 21',
    client: 'KESZ, Hungary',
    project_type: 'Contruction, Brading',
    location: 'Mountain View CA 94043',
    year: '2021',
  },
  {
    id: '1',
    name: 'Startup Product Sales',
    slogan: 'Creating quality urban lifestyles, building stronger communities',
    date: 'Jan 10, 20',
    client: 'Studio Massimo, Italy',
    project_type: 'Contruction, Spa',
    location: 'Budapest 1149',
    year: '2020',
  },
  {
    id: '2',
    name: 'Monopoly Market',
    slogan: 'Helping you and your house become better acquinted',
    date: 'April 10, 21',
    client: 'KESZ, Hungary',
    project_type: 'Contruction, Brading',
    location: 'Mountain View CA 94043',
    year: '2021',
  },
  {
    id: '3',
    name: 'Creative Market',
    slogan: 'Creating quality urban lifestyles, building stronger communities',
    date: 'Jan 10, 20',
    client: 'Studio Massimo, Italy',
    project_type: 'Contruction, Spa',
    location: 'Budapest 1149',
    year: '2020',
  },
  {
    id: '4',
    name: 'Startup Product Sales',
    slogan: 'Helping you and your house become better acquinted',
    date: 'April 10, 21',
    client: 'KESZ, Hungary',
    project_type: 'Contruction, Brading',
    location: 'Mountain View CA 94043',
    year: '2021',
  },
  {
    id: '5',
    name: 'Monopoly Market',
    slogan: 'Creating quality urban lifestyles, building stronger communities',
    date: 'Jan 10, 20',
    client: 'Studio Massimo, Italy',
    project_type: 'Contruction, Spa',
    location: 'Budapest 1149',
    year: '2020',
  },
];
